version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "3003:3003"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=VilattaRomina
      - DB_NAME=merobaron
      - DB_PORT=3306
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:3003

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=VilattaRomina
      - MYSQL_DATABASE=merobaron
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
