import { Roboto } from 'next/font/google'
import './globals.css'
import Script from 'next/script'
import { LocationProvider } from './context/LocationContext'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <LocationProvider>
      <html lang='es'>
        <body className={roboto.className}>
          {children}
          <Script
            src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}
            strategy='beforeInteractive'
          />
        </body>
      </html>
    </LocationProvider>
  )
}
